# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: dhis2gw
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - "-s -w"
    goos:
      - linux
      # - windows
      - darwin
archives:
  - files:
      - README.md
      # - db/**/*.sql
      - db/**/*.*
      - docs/md_docs/**/*
      - docs/static/**/*
      - docs/templates/**/*
checksum:
  name_template: 'checksums.txt'
snapshot:
  # name_template: "{{ incpatch .Version }}"
  name_template: "{{ .Version }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^test:'
