// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package pbs

import (
	"context"
	"time"

	"github.com/Khan/genqlient/graphql"
)

// CgBudgetOutturnsByFiscalYearCgBudgetOutturnByFiscalYearOpmCgBudgetOutturnDto includes the requested fields of the GraphQL type OpmCgBudgetOutturnDto.
type CgBudgetOutturnsByFiscalYearCgBudgetOutturnByFiscalYearOpmCgBudgetOutturnDto struct {
	Fiscal_Year               string  `json:"Fiscal_Year"`
	Vote_Code                 string  `json:"Vote_Code"`
	Vote_Name                 string  `json:"Vote_Name"`
	Programme_Code            string  `json:"Programme_Code"`
	Programme_Name            string  `json:"Programme_Name"`
	Department_Code           string  `json:"Department_Code"`
	Department_Name           string  `json:"Department_Name"`
	Project_Code              string  `json:"Project_Code"`
	Budget_Output_Code        string  `json:"Budget_Output_Code"`
	Budget_Output_Description string  `json:"Budget_Output_Description"`
	Item_Code                 string  `json:"Item_Code"`
	Item_Description          string  `json:"Item_Description"`
	ApprovedBudget            float64 `json:"ApprovedBudget"`
	RevisedBudget             float64 `json:"RevisedBudget"`
	Q1Release                 float64 `json:"Q1Release"`
	Q1Expenditure             float64 `json:"Q1Expenditure"`
	Q2Release                 float64 `json:"Q2Release"`
	Q2Expenditure             float64 `json:"Q2Expenditure"`
	Q3Release                 float64 `json:"Q3Release"`
	Q3Expenditure             float64 `json:"Q3Expenditure"`
	Q4Release                 float64 `json:"Q4Release"`
	Q4Expenditure             float64 `json:"Q4Expenditure"`
}

// GetFiscal_Year returns CgBudgetOutturnsByFiscalYearCgBudgetOutturnByFiscalYearOpmCgBudgetOutturnDto.Fiscal_Year, and is useful for accessing the field via an interface.
func (v *CgBudgetOutturnsByFiscalYearCgBudgetOutturnByFiscalYearOpmCgBudgetOutturnDto) GetFiscal_Year() string {
	return v.Fiscal_Year
}

// GetVote_Code returns CgBudgetOutturnsByFiscalYearCgBudgetOutturnByFiscalYearOpmCgBudgetOutturnDto.Vote_Code, and is useful for accessing the field via an interface.
func (v *CgBudgetOutturnsByFiscalYearCgBudgetOutturnByFiscalYearOpmCgBudgetOutturnDto) GetVote_Code() string {
	return v.Vote_Code
}

// GetVote_Name returns CgBudgetOutturnsByFiscalYearCgBudgetOutturnByFiscalYearOpmCgBudgetOutturnDto.Vote_Name, and is useful for accessing the field via an interface.
func (v *CgBudgetOutturnsByFiscalYearCgBudgetOutturnByFiscalYearOpmCgBudgetOutturnDto) GetVote_Name() string {
	return v.Vote_Name
}

// GetProgramme_Code returns CgBudgetOutturnsByFiscalYearCgBudgetOutturnByFiscalYearOpmCgBudgetOutturnDto.Programme_Code, and is useful for accessing the field via an interface.
func (v *CgBudgetOutturnsByFiscalYearCgBudgetOutturnByFiscalYearOpmCgBudgetOutturnDto) GetProgramme_Code() string {
	return v.Programme_Code
}

// GetProgramme_Name returns CgBudgetOutturnsByFiscalYearCgBudgetOutturnByFiscalYearOpmCgBudgetOutturnDto.Programme_Name, and is useful for accessing the field via an interface.
func (v *CgBudgetOutturnsByFiscalYearCgBudgetOutturnByFiscalYearOpmCgBudgetOutturnDto) GetProgramme_Name() string {
	return v.Programme_Name
}

// GetDepartment_Code returns CgBudgetOutturnsByFiscalYearCgBudgetOutturnByFiscalYearOpmCgBudgetOutturnDto.Department_Code, and is useful for accessing the field via an interface.
func (v *CgBudgetOutturnsByFiscalYearCgBudgetOutturnByFiscalYearOpmCgBudgetOutturnDto) GetDepartment_Code() string {
	return v.Department_Code
}

// GetDepartment_Name returns CgBudgetOutturnsByFiscalYearCgBudgetOutturnByFiscalYearOpmCgBudgetOutturnDto.Department_Name, and is useful for accessing the field via an interface.
func (v *CgBudgetOutturnsByFiscalYearCgBudgetOutturnByFiscalYearOpmCgBudgetOutturnDto) GetDepartment_Name() string {
	return v.Department_Name
}

// GetProject_Code returns CgBudgetOutturnsByFiscalYearCgBudgetOutturnByFiscalYearOpmCgBudgetOutturnDto.Project_Code, and is useful for accessing the field via an interface.
func (v *CgBudgetOutturnsByFiscalYearCgBudgetOutturnByFiscalYearOpmCgBudgetOutturnDto) GetProject_Code() string {
	return v.Project_Code
}

// GetBudget_Output_Code returns CgBudgetOutturnsByFiscalYearCgBudgetOutturnByFiscalYearOpmCgBudgetOutturnDto.Budget_Output_Code, and is useful for accessing the field via an interface.
func (v *CgBudgetOutturnsByFiscalYearCgBudgetOutturnByFiscalYearOpmCgBudgetOutturnDto) GetBudget_Output_Code() string {
	return v.Budget_Output_Code
}

// GetBudget_Output_Description returns CgBudgetOutturnsByFiscalYearCgBudgetOutturnByFiscalYearOpmCgBudgetOutturnDto.Budget_Output_Description, and is useful for accessing the field via an interface.
func (v *CgBudgetOutturnsByFiscalYearCgBudgetOutturnByFiscalYearOpmCgBudgetOutturnDto) GetBudget_Output_Description() string {
	return v.Budget_Output_Description
}

// GetItem_Code returns CgBudgetOutturnsByFiscalYearCgBudgetOutturnByFiscalYearOpmCgBudgetOutturnDto.Item_Code, and is useful for accessing the field via an interface.
func (v *CgBudgetOutturnsByFiscalYearCgBudgetOutturnByFiscalYearOpmCgBudgetOutturnDto) GetItem_Code() string {
	return v.Item_Code
}

// GetItem_Description returns CgBudgetOutturnsByFiscalYearCgBudgetOutturnByFiscalYearOpmCgBudgetOutturnDto.Item_Description, and is useful for accessing the field via an interface.
func (v *CgBudgetOutturnsByFiscalYearCgBudgetOutturnByFiscalYearOpmCgBudgetOutturnDto) GetItem_Description() string {
	return v.Item_Description
}

// GetApprovedBudget returns CgBudgetOutturnsByFiscalYearCgBudgetOutturnByFiscalYearOpmCgBudgetOutturnDto.ApprovedBudget, and is useful for accessing the field via an interface.
func (v *CgBudgetOutturnsByFiscalYearCgBudgetOutturnByFiscalYearOpmCgBudgetOutturnDto) GetApprovedBudget() float64 {
	return v.ApprovedBudget
}

// GetRevisedBudget returns CgBudgetOutturnsByFiscalYearCgBudgetOutturnByFiscalYearOpmCgBudgetOutturnDto.RevisedBudget, and is useful for accessing the field via an interface.
func (v *CgBudgetOutturnsByFiscalYearCgBudgetOutturnByFiscalYearOpmCgBudgetOutturnDto) GetRevisedBudget() float64 {
	return v.RevisedBudget
}

// GetQ1Release returns CgBudgetOutturnsByFiscalYearCgBudgetOutturnByFiscalYearOpmCgBudgetOutturnDto.Q1Release, and is useful for accessing the field via an interface.
func (v *CgBudgetOutturnsByFiscalYearCgBudgetOutturnByFiscalYearOpmCgBudgetOutturnDto) GetQ1Release() float64 {
	return v.Q1Release
}

// GetQ1Expenditure returns CgBudgetOutturnsByFiscalYearCgBudgetOutturnByFiscalYearOpmCgBudgetOutturnDto.Q1Expenditure, and is useful for accessing the field via an interface.
func (v *CgBudgetOutturnsByFiscalYearCgBudgetOutturnByFiscalYearOpmCgBudgetOutturnDto) GetQ1Expenditure() float64 {
	return v.Q1Expenditure
}

// GetQ2Release returns CgBudgetOutturnsByFiscalYearCgBudgetOutturnByFiscalYearOpmCgBudgetOutturnDto.Q2Release, and is useful for accessing the field via an interface.
func (v *CgBudgetOutturnsByFiscalYearCgBudgetOutturnByFiscalYearOpmCgBudgetOutturnDto) GetQ2Release() float64 {
	return v.Q2Release
}

// GetQ2Expenditure returns CgBudgetOutturnsByFiscalYearCgBudgetOutturnByFiscalYearOpmCgBudgetOutturnDto.Q2Expenditure, and is useful for accessing the field via an interface.
func (v *CgBudgetOutturnsByFiscalYearCgBudgetOutturnByFiscalYearOpmCgBudgetOutturnDto) GetQ2Expenditure() float64 {
	return v.Q2Expenditure
}

// GetQ3Release returns CgBudgetOutturnsByFiscalYearCgBudgetOutturnByFiscalYearOpmCgBudgetOutturnDto.Q3Release, and is useful for accessing the field via an interface.
func (v *CgBudgetOutturnsByFiscalYearCgBudgetOutturnByFiscalYearOpmCgBudgetOutturnDto) GetQ3Release() float64 {
	return v.Q3Release
}

// GetQ3Expenditure returns CgBudgetOutturnsByFiscalYearCgBudgetOutturnByFiscalYearOpmCgBudgetOutturnDto.Q3Expenditure, and is useful for accessing the field via an interface.
func (v *CgBudgetOutturnsByFiscalYearCgBudgetOutturnByFiscalYearOpmCgBudgetOutturnDto) GetQ3Expenditure() float64 {
	return v.Q3Expenditure
}

// GetQ4Release returns CgBudgetOutturnsByFiscalYearCgBudgetOutturnByFiscalYearOpmCgBudgetOutturnDto.Q4Release, and is useful for accessing the field via an interface.
func (v *CgBudgetOutturnsByFiscalYearCgBudgetOutturnByFiscalYearOpmCgBudgetOutturnDto) GetQ4Release() float64 {
	return v.Q4Release
}

// GetQ4Expenditure returns CgBudgetOutturnsByFiscalYearCgBudgetOutturnByFiscalYearOpmCgBudgetOutturnDto.Q4Expenditure, and is useful for accessing the field via an interface.
func (v *CgBudgetOutturnsByFiscalYearCgBudgetOutturnByFiscalYearOpmCgBudgetOutturnDto) GetQ4Expenditure() float64 {
	return v.Q4Expenditure
}

// CgBudgetOutturnsByFiscalYearResponse is returned by CgBudgetOutturnsByFiscalYear on success.
type CgBudgetOutturnsByFiscalYearResponse struct {
	CgBudgetOutturnByFiscalYear []CgBudgetOutturnsByFiscalYearCgBudgetOutturnByFiscalYearOpmCgBudgetOutturnDto `json:"cgBudgetOutturnByFiscalYear"`
}

// GetCgBudgetOutturnByFiscalYear returns CgBudgetOutturnsByFiscalYearResponse.CgBudgetOutturnByFiscalYear, and is useful for accessing the field via an interface.
func (v *CgBudgetOutturnsByFiscalYearResponse) GetCgBudgetOutturnByFiscalYear() []CgBudgetOutturnsByFiscalYearCgBudgetOutturnByFiscalYearOpmCgBudgetOutturnDto {
	return v.CgBudgetOutturnByFiscalYear
}

// CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto includes the requested fields of the GraphQL type OpmCgPiapIndicatorProjectionsDto.
type CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto struct {
	Fiscal_Year                string `json:"Fiscal_Year"`
	Vote_Code                  string `json:"Vote_Code"`
	Vote_Name                  string `json:"Vote_Name"`
	Programme_Code             string `json:"Programme_Code"`
	Programme_Name             string `json:"Programme_Name"`
	Department_Code            string `json:"Department_Code"`
	Department_Name            string `json:"Department_Name"`
	Budget_Output_Code         string `json:"Budget_Output_Code"`
	Budget_Output_Description  string `json:"Budget_Output_Description"`
	Target_Y1                  string `json:"Target_Y1"`
	PIAP_Output_Code           string `json:"PIAP_Output_Code"`
	PIAP_Output_Description    string `json:"PIAP_Output_Description"`
	PIAP_Output_Indicator_Code string `json:"PIAP_Output_Indicator_Code"`
	PIAP_Output_Indicator_Name string `json:"PIAP_Output_Indicator_Name"`
	Q1_Actual_Target           string `json:"Q1_Actual_Target"`
	Q1_Reason_For_Variation    string `json:"Q1_Reason_For_Variation"`
	Q2_Actual_Target           string `json:"Q2_Actual_Target"`
	Q2_Reason_For_Variation    string `json:"Q2_Reason_For_Variation"`
	Q2_Cum_Performance         string `json:"Q2_Cum_Performance"`
	Q3_Actual_Target           string `json:"Q3_Actual_Target"`
	Q3_Reason_For_Variation    string `json:"Q3_Reason_For_Variation"`
	Q3_Cum_Performance         string `json:"Q3_Cum_Performance"`
	Q4_Actual_Target           string `json:"Q4_Actual_Target"`
	Q4_Reason_For_Variation    string `json:"Q4_Reason_For_Variation"`
	Q4_Cum_Performance         string `json:"Q4_Cum_Performance"`
}

// GetFiscal_Year returns CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto.Fiscal_Year, and is useful for accessing the field via an interface.
func (v *CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto) GetFiscal_Year() string {
	return v.Fiscal_Year
}

// GetVote_Code returns CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto.Vote_Code, and is useful for accessing the field via an interface.
func (v *CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto) GetVote_Code() string {
	return v.Vote_Code
}

// GetVote_Name returns CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto.Vote_Name, and is useful for accessing the field via an interface.
func (v *CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto) GetVote_Name() string {
	return v.Vote_Name
}

// GetProgramme_Code returns CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto.Programme_Code, and is useful for accessing the field via an interface.
func (v *CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto) GetProgramme_Code() string {
	return v.Programme_Code
}

// GetProgramme_Name returns CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto.Programme_Name, and is useful for accessing the field via an interface.
func (v *CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto) GetProgramme_Name() string {
	return v.Programme_Name
}

// GetDepartment_Code returns CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto.Department_Code, and is useful for accessing the field via an interface.
func (v *CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto) GetDepartment_Code() string {
	return v.Department_Code
}

// GetDepartment_Name returns CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto.Department_Name, and is useful for accessing the field via an interface.
func (v *CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto) GetDepartment_Name() string {
	return v.Department_Name
}

// GetBudget_Output_Code returns CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto.Budget_Output_Code, and is useful for accessing the field via an interface.
func (v *CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto) GetBudget_Output_Code() string {
	return v.Budget_Output_Code
}

// GetBudget_Output_Description returns CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto.Budget_Output_Description, and is useful for accessing the field via an interface.
func (v *CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto) GetBudget_Output_Description() string {
	return v.Budget_Output_Description
}

// GetTarget_Y1 returns CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto.Target_Y1, and is useful for accessing the field via an interface.
func (v *CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto) GetTarget_Y1() string {
	return v.Target_Y1
}

// GetPIAP_Output_Code returns CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto.PIAP_Output_Code, and is useful for accessing the field via an interface.
func (v *CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto) GetPIAP_Output_Code() string {
	return v.PIAP_Output_Code
}

// GetPIAP_Output_Description returns CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto.PIAP_Output_Description, and is useful for accessing the field via an interface.
func (v *CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto) GetPIAP_Output_Description() string {
	return v.PIAP_Output_Description
}

// GetPIAP_Output_Indicator_Code returns CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto.PIAP_Output_Indicator_Code, and is useful for accessing the field via an interface.
func (v *CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto) GetPIAP_Output_Indicator_Code() string {
	return v.PIAP_Output_Indicator_Code
}

// GetPIAP_Output_Indicator_Name returns CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto.PIAP_Output_Indicator_Name, and is useful for accessing the field via an interface.
func (v *CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto) GetPIAP_Output_Indicator_Name() string {
	return v.PIAP_Output_Indicator_Name
}

// GetQ1_Actual_Target returns CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto.Q1_Actual_Target, and is useful for accessing the field via an interface.
func (v *CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto) GetQ1_Actual_Target() string {
	return v.Q1_Actual_Target
}

// GetQ1_Reason_For_Variation returns CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto.Q1_Reason_For_Variation, and is useful for accessing the field via an interface.
func (v *CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto) GetQ1_Reason_For_Variation() string {
	return v.Q1_Reason_For_Variation
}

// GetQ2_Actual_Target returns CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto.Q2_Actual_Target, and is useful for accessing the field via an interface.
func (v *CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto) GetQ2_Actual_Target() string {
	return v.Q2_Actual_Target
}

// GetQ2_Reason_For_Variation returns CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto.Q2_Reason_For_Variation, and is useful for accessing the field via an interface.
func (v *CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto) GetQ2_Reason_For_Variation() string {
	return v.Q2_Reason_For_Variation
}

// GetQ2_Cum_Performance returns CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto.Q2_Cum_Performance, and is useful for accessing the field via an interface.
func (v *CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto) GetQ2_Cum_Performance() string {
	return v.Q2_Cum_Performance
}

// GetQ3_Actual_Target returns CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto.Q3_Actual_Target, and is useful for accessing the field via an interface.
func (v *CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto) GetQ3_Actual_Target() string {
	return v.Q3_Actual_Target
}

// GetQ3_Reason_For_Variation returns CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto.Q3_Reason_For_Variation, and is useful for accessing the field via an interface.
func (v *CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto) GetQ3_Reason_For_Variation() string {
	return v.Q3_Reason_For_Variation
}

// GetQ3_Cum_Performance returns CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto.Q3_Cum_Performance, and is useful for accessing the field via an interface.
func (v *CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto) GetQ3_Cum_Performance() string {
	return v.Q3_Cum_Performance
}

// GetQ4_Actual_Target returns CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto.Q4_Actual_Target, and is useful for accessing the field via an interface.
func (v *CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto) GetQ4_Actual_Target() string {
	return v.Q4_Actual_Target
}

// GetQ4_Reason_For_Variation returns CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto.Q4_Reason_For_Variation, and is useful for accessing the field via an interface.
func (v *CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto) GetQ4_Reason_For_Variation() string {
	return v.Q4_Reason_For_Variation
}

// GetQ4_Cum_Performance returns CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto.Q4_Cum_Performance, and is useful for accessing the field via an interface.
func (v *CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto) GetQ4_Cum_Performance() string {
	return v.Q4_Cum_Performance
}

// CgPiapIndicatorProjectionsByFiscalYearResponse is returned by CgPiapIndicatorProjectionsByFiscalYear on success.
type CgPiapIndicatorProjectionsByFiscalYearResponse struct {
	CgPiapIndicatorProjectionsByFiscalYear []CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto `json:"cgPiapIndicatorProjectionsByFiscalYear"`
}

// GetCgPiapIndicatorProjectionsByFiscalYear returns CgPiapIndicatorProjectionsByFiscalYearResponse.CgPiapIndicatorProjectionsByFiscalYear, and is useful for accessing the field via an interface.
func (v *CgPiapIndicatorProjectionsByFiscalYearResponse) GetCgPiapIndicatorProjectionsByFiscalYear() []CgPiapIndicatorProjectionsByFiscalYearCgPiapIndicatorProjectionsByFiscalYearOpmCgPiapIndicatorProjectionsDto {
	return v.CgPiapIndicatorProjectionsByFiscalYear
}

// CgProgrammeOutcomeIndicatorProjectionsByFiscalYearCgProgrammeOutcomeIndicatorProjectionsByFiscalYearOpmCgProgrammeOutcomeIndicatorProjectionDto includes the requested fields of the GraphQL type OpmCgProgrammeOutcomeIndicatorProjectionDto.
type CgProgrammeOutcomeIndicatorProjectionsByFiscalYearCgProgrammeOutcomeIndicatorProjectionsByFiscalYearOpmCgProgrammeOutcomeIndicatorProjectionDto struct {
	Fiscal_Year                             string `json:"Fiscal_Year"`
	Programme_Code                          string `json:"Programme_Code"`
	Programme_Name                          string `json:"Programme_Name"`
	Programme_Objective_Code                string `json:"Programme_Objective_Code"`
	Programme_Objective_Name                string `json:"Programme_Objective_Name"`
	Programme_Outcome_Code                  string `json:"Programme_Outcome_Code"`
	Programme_Outcome_Description           string `json:"Programme_Outcome_Description"`
	Programme_Outcome_Indicator_Code        string `json:"Programme_Outcome_Indicator_Code"`
	Programme_Outcome_Indicator_Description string `json:"Programme_Outcome_Indicator_Description"`
	Target_Y1                               string `json:"Target_Y1"`
	Q2_Actual                               string `json:"Q2_Actual"`
	Q2_Reason_For_Variation                 string `json:"Q2_Reason_For_Variation"`
	Q4_Actual                               string `json:"Q4_Actual"`
	Q4_Reason_For_Variation                 string `json:"Q4_Reason_For_Variation"`
}

// GetFiscal_Year returns CgProgrammeOutcomeIndicatorProjectionsByFiscalYearCgProgrammeOutcomeIndicatorProjectionsByFiscalYearOpmCgProgrammeOutcomeIndicatorProjectionDto.Fiscal_Year, and is useful for accessing the field via an interface.
func (v *CgProgrammeOutcomeIndicatorProjectionsByFiscalYearCgProgrammeOutcomeIndicatorProjectionsByFiscalYearOpmCgProgrammeOutcomeIndicatorProjectionDto) GetFiscal_Year() string {
	return v.Fiscal_Year
}

// GetProgramme_Code returns CgProgrammeOutcomeIndicatorProjectionsByFiscalYearCgProgrammeOutcomeIndicatorProjectionsByFiscalYearOpmCgProgrammeOutcomeIndicatorProjectionDto.Programme_Code, and is useful for accessing the field via an interface.
func (v *CgProgrammeOutcomeIndicatorProjectionsByFiscalYearCgProgrammeOutcomeIndicatorProjectionsByFiscalYearOpmCgProgrammeOutcomeIndicatorProjectionDto) GetProgramme_Code() string {
	return v.Programme_Code
}

// GetProgramme_Name returns CgProgrammeOutcomeIndicatorProjectionsByFiscalYearCgProgrammeOutcomeIndicatorProjectionsByFiscalYearOpmCgProgrammeOutcomeIndicatorProjectionDto.Programme_Name, and is useful for accessing the field via an interface.
func (v *CgProgrammeOutcomeIndicatorProjectionsByFiscalYearCgProgrammeOutcomeIndicatorProjectionsByFiscalYearOpmCgProgrammeOutcomeIndicatorProjectionDto) GetProgramme_Name() string {
	return v.Programme_Name
}

// GetProgramme_Objective_Code returns CgProgrammeOutcomeIndicatorProjectionsByFiscalYearCgProgrammeOutcomeIndicatorProjectionsByFiscalYearOpmCgProgrammeOutcomeIndicatorProjectionDto.Programme_Objective_Code, and is useful for accessing the field via an interface.
func (v *CgProgrammeOutcomeIndicatorProjectionsByFiscalYearCgProgrammeOutcomeIndicatorProjectionsByFiscalYearOpmCgProgrammeOutcomeIndicatorProjectionDto) GetProgramme_Objective_Code() string {
	return v.Programme_Objective_Code
}

// GetProgramme_Objective_Name returns CgProgrammeOutcomeIndicatorProjectionsByFiscalYearCgProgrammeOutcomeIndicatorProjectionsByFiscalYearOpmCgProgrammeOutcomeIndicatorProjectionDto.Programme_Objective_Name, and is useful for accessing the field via an interface.
func (v *CgProgrammeOutcomeIndicatorProjectionsByFiscalYearCgProgrammeOutcomeIndicatorProjectionsByFiscalYearOpmCgProgrammeOutcomeIndicatorProjectionDto) GetProgramme_Objective_Name() string {
	return v.Programme_Objective_Name
}

// GetProgramme_Outcome_Code returns CgProgrammeOutcomeIndicatorProjectionsByFiscalYearCgProgrammeOutcomeIndicatorProjectionsByFiscalYearOpmCgProgrammeOutcomeIndicatorProjectionDto.Programme_Outcome_Code, and is useful for accessing the field via an interface.
func (v *CgProgrammeOutcomeIndicatorProjectionsByFiscalYearCgProgrammeOutcomeIndicatorProjectionsByFiscalYearOpmCgProgrammeOutcomeIndicatorProjectionDto) GetProgramme_Outcome_Code() string {
	return v.Programme_Outcome_Code
}

// GetProgramme_Outcome_Description returns CgProgrammeOutcomeIndicatorProjectionsByFiscalYearCgProgrammeOutcomeIndicatorProjectionsByFiscalYearOpmCgProgrammeOutcomeIndicatorProjectionDto.Programme_Outcome_Description, and is useful for accessing the field via an interface.
func (v *CgProgrammeOutcomeIndicatorProjectionsByFiscalYearCgProgrammeOutcomeIndicatorProjectionsByFiscalYearOpmCgProgrammeOutcomeIndicatorProjectionDto) GetProgramme_Outcome_Description() string {
	return v.Programme_Outcome_Description
}

// GetProgramme_Outcome_Indicator_Code returns CgProgrammeOutcomeIndicatorProjectionsByFiscalYearCgProgrammeOutcomeIndicatorProjectionsByFiscalYearOpmCgProgrammeOutcomeIndicatorProjectionDto.Programme_Outcome_Indicator_Code, and is useful for accessing the field via an interface.
func (v *CgProgrammeOutcomeIndicatorProjectionsByFiscalYearCgProgrammeOutcomeIndicatorProjectionsByFiscalYearOpmCgProgrammeOutcomeIndicatorProjectionDto) GetProgramme_Outcome_Indicator_Code() string {
	return v.Programme_Outcome_Indicator_Code
}

// GetProgramme_Outcome_Indicator_Description returns CgProgrammeOutcomeIndicatorProjectionsByFiscalYearCgProgrammeOutcomeIndicatorProjectionsByFiscalYearOpmCgProgrammeOutcomeIndicatorProjectionDto.Programme_Outcome_Indicator_Description, and is useful for accessing the field via an interface.
func (v *CgProgrammeOutcomeIndicatorProjectionsByFiscalYearCgProgrammeOutcomeIndicatorProjectionsByFiscalYearOpmCgProgrammeOutcomeIndicatorProjectionDto) GetProgramme_Outcome_Indicator_Description() string {
	return v.Programme_Outcome_Indicator_Description
}

// GetTarget_Y1 returns CgProgrammeOutcomeIndicatorProjectionsByFiscalYearCgProgrammeOutcomeIndicatorProjectionsByFiscalYearOpmCgProgrammeOutcomeIndicatorProjectionDto.Target_Y1, and is useful for accessing the field via an interface.
func (v *CgProgrammeOutcomeIndicatorProjectionsByFiscalYearCgProgrammeOutcomeIndicatorProjectionsByFiscalYearOpmCgProgrammeOutcomeIndicatorProjectionDto) GetTarget_Y1() string {
	return v.Target_Y1
}

// GetQ2_Actual returns CgProgrammeOutcomeIndicatorProjectionsByFiscalYearCgProgrammeOutcomeIndicatorProjectionsByFiscalYearOpmCgProgrammeOutcomeIndicatorProjectionDto.Q2_Actual, and is useful for accessing the field via an interface.
func (v *CgProgrammeOutcomeIndicatorProjectionsByFiscalYearCgProgrammeOutcomeIndicatorProjectionsByFiscalYearOpmCgProgrammeOutcomeIndicatorProjectionDto) GetQ2_Actual() string {
	return v.Q2_Actual
}

// GetQ2_Reason_For_Variation returns CgProgrammeOutcomeIndicatorProjectionsByFiscalYearCgProgrammeOutcomeIndicatorProjectionsByFiscalYearOpmCgProgrammeOutcomeIndicatorProjectionDto.Q2_Reason_For_Variation, and is useful for accessing the field via an interface.
func (v *CgProgrammeOutcomeIndicatorProjectionsByFiscalYearCgProgrammeOutcomeIndicatorProjectionsByFiscalYearOpmCgProgrammeOutcomeIndicatorProjectionDto) GetQ2_Reason_For_Variation() string {
	return v.Q2_Reason_For_Variation
}

// GetQ4_Actual returns CgProgrammeOutcomeIndicatorProjectionsByFiscalYearCgProgrammeOutcomeIndicatorProjectionsByFiscalYearOpmCgProgrammeOutcomeIndicatorProjectionDto.Q4_Actual, and is useful for accessing the field via an interface.
func (v *CgProgrammeOutcomeIndicatorProjectionsByFiscalYearCgProgrammeOutcomeIndicatorProjectionsByFiscalYearOpmCgProgrammeOutcomeIndicatorProjectionDto) GetQ4_Actual() string {
	return v.Q4_Actual
}

// GetQ4_Reason_For_Variation returns CgProgrammeOutcomeIndicatorProjectionsByFiscalYearCgProgrammeOutcomeIndicatorProjectionsByFiscalYearOpmCgProgrammeOutcomeIndicatorProjectionDto.Q4_Reason_For_Variation, and is useful for accessing the field via an interface.
func (v *CgProgrammeOutcomeIndicatorProjectionsByFiscalYearCgProgrammeOutcomeIndicatorProjectionsByFiscalYearOpmCgProgrammeOutcomeIndicatorProjectionDto) GetQ4_Reason_For_Variation() string {
	return v.Q4_Reason_For_Variation
}

// CgProgrammeOutcomeIndicatorProjectionsByFiscalYearResponse is returned by CgProgrammeOutcomeIndicatorProjectionsByFiscalYear on success.
type CgProgrammeOutcomeIndicatorProjectionsByFiscalYearResponse struct {
	CgProgrammeOutcomeIndicatorProjectionsByFiscalYear []CgProgrammeOutcomeIndicatorProjectionsByFiscalYearCgProgrammeOutcomeIndicatorProjectionsByFiscalYearOpmCgProgrammeOutcomeIndicatorProjectionDto `json:"cgProgrammeOutcomeIndicatorProjectionsByFiscalYear"`
}

// GetCgProgrammeOutcomeIndicatorProjectionsByFiscalYear returns CgProgrammeOutcomeIndicatorProjectionsByFiscalYearResponse.CgProgrammeOutcomeIndicatorProjectionsByFiscalYear, and is useful for accessing the field via an interface.
func (v *CgProgrammeOutcomeIndicatorProjectionsByFiscalYearResponse) GetCgProgrammeOutcomeIndicatorProjectionsByFiscalYear() []CgProgrammeOutcomeIndicatorProjectionsByFiscalYearCgProgrammeOutcomeIndicatorProjectionsByFiscalYearOpmCgProgrammeOutcomeIndicatorProjectionDto {
	return v.CgProgrammeOutcomeIndicatorProjectionsByFiscalYear
}

// LgBudgetOutturnsByFiscalYearLgBudgetOutturnsByFiscalYearOpmLgBudgetOutturnDto includes the requested fields of the GraphQL type OpmLgBudgetOutturnDto.
type LgBudgetOutturnsByFiscalYearLgBudgetOutturnsByFiscalYearOpmLgBudgetOutturnDto struct {
	Fiscal_Year               string  `json:"Fiscal_Year"`
	Vote_Code                 string  `json:"Vote_Code"`
	Vote_Name                 string  `json:"Vote_Name"`
	Programme_Code            string  `json:"Programme_Code"`
	Programme_Name            string  `json:"Programme_Name"`
	Department_Code           string  `json:"Department_Code"`
	Department_Name           string  `json:"Department_Name"`
	Project_Code              string  `json:"Project_Code"`
	Budget_Output_Code        string  `json:"Budget_Output_Code"`
	Budget_Output_Description string  `json:"Budget_Output_Description"`
	Item_Code                 string  `json:"Item_Code"`
	Item_Description          string  `json:"Item_Description"`
	ApprovedBudget            float64 `json:"ApprovedBudget"`
	RevisedBudget             float64 `json:"RevisedBudget"`
	Q1_Release                float64 `json:"Q1_Release"`
	Q1_Expenditure            float64 `json:"Q1_Expenditure"`
	Q2_Release                float64 `json:"Q2_Release"`
	Q2_Expenditure            float64 `json:"Q2_Expenditure"`
	Q3_Release                float64 `json:"Q3_Release"`
	Q3_Expenditure            float64 `json:"Q3_Expenditure"`
	Q4_Release                float64 `json:"Q4_Release"`
	Q4_Expenditure            float64 `json:"Q4_Expenditure"`
}

// GetFiscal_Year returns LgBudgetOutturnsByFiscalYearLgBudgetOutturnsByFiscalYearOpmLgBudgetOutturnDto.Fiscal_Year, and is useful for accessing the field via an interface.
func (v *LgBudgetOutturnsByFiscalYearLgBudgetOutturnsByFiscalYearOpmLgBudgetOutturnDto) GetFiscal_Year() string {
	return v.Fiscal_Year
}

// GetVote_Code returns LgBudgetOutturnsByFiscalYearLgBudgetOutturnsByFiscalYearOpmLgBudgetOutturnDto.Vote_Code, and is useful for accessing the field via an interface.
func (v *LgBudgetOutturnsByFiscalYearLgBudgetOutturnsByFiscalYearOpmLgBudgetOutturnDto) GetVote_Code() string {
	return v.Vote_Code
}

// GetVote_Name returns LgBudgetOutturnsByFiscalYearLgBudgetOutturnsByFiscalYearOpmLgBudgetOutturnDto.Vote_Name, and is useful for accessing the field via an interface.
func (v *LgBudgetOutturnsByFiscalYearLgBudgetOutturnsByFiscalYearOpmLgBudgetOutturnDto) GetVote_Name() string {
	return v.Vote_Name
}

// GetProgramme_Code returns LgBudgetOutturnsByFiscalYearLgBudgetOutturnsByFiscalYearOpmLgBudgetOutturnDto.Programme_Code, and is useful for accessing the field via an interface.
func (v *LgBudgetOutturnsByFiscalYearLgBudgetOutturnsByFiscalYearOpmLgBudgetOutturnDto) GetProgramme_Code() string {
	return v.Programme_Code
}

// GetProgramme_Name returns LgBudgetOutturnsByFiscalYearLgBudgetOutturnsByFiscalYearOpmLgBudgetOutturnDto.Programme_Name, and is useful for accessing the field via an interface.
func (v *LgBudgetOutturnsByFiscalYearLgBudgetOutturnsByFiscalYearOpmLgBudgetOutturnDto) GetProgramme_Name() string {
	return v.Programme_Name
}

// GetDepartment_Code returns LgBudgetOutturnsByFiscalYearLgBudgetOutturnsByFiscalYearOpmLgBudgetOutturnDto.Department_Code, and is useful for accessing the field via an interface.
func (v *LgBudgetOutturnsByFiscalYearLgBudgetOutturnsByFiscalYearOpmLgBudgetOutturnDto) GetDepartment_Code() string {
	return v.Department_Code
}

// GetDepartment_Name returns LgBudgetOutturnsByFiscalYearLgBudgetOutturnsByFiscalYearOpmLgBudgetOutturnDto.Department_Name, and is useful for accessing the field via an interface.
func (v *LgBudgetOutturnsByFiscalYearLgBudgetOutturnsByFiscalYearOpmLgBudgetOutturnDto) GetDepartment_Name() string {
	return v.Department_Name
}

// GetProject_Code returns LgBudgetOutturnsByFiscalYearLgBudgetOutturnsByFiscalYearOpmLgBudgetOutturnDto.Project_Code, and is useful for accessing the field via an interface.
func (v *LgBudgetOutturnsByFiscalYearLgBudgetOutturnsByFiscalYearOpmLgBudgetOutturnDto) GetProject_Code() string {
	return v.Project_Code
}

// GetBudget_Output_Code returns LgBudgetOutturnsByFiscalYearLgBudgetOutturnsByFiscalYearOpmLgBudgetOutturnDto.Budget_Output_Code, and is useful for accessing the field via an interface.
func (v *LgBudgetOutturnsByFiscalYearLgBudgetOutturnsByFiscalYearOpmLgBudgetOutturnDto) GetBudget_Output_Code() string {
	return v.Budget_Output_Code
}

// GetBudget_Output_Description returns LgBudgetOutturnsByFiscalYearLgBudgetOutturnsByFiscalYearOpmLgBudgetOutturnDto.Budget_Output_Description, and is useful for accessing the field via an interface.
func (v *LgBudgetOutturnsByFiscalYearLgBudgetOutturnsByFiscalYearOpmLgBudgetOutturnDto) GetBudget_Output_Description() string {
	return v.Budget_Output_Description
}

// GetItem_Code returns LgBudgetOutturnsByFiscalYearLgBudgetOutturnsByFiscalYearOpmLgBudgetOutturnDto.Item_Code, and is useful for accessing the field via an interface.
func (v *LgBudgetOutturnsByFiscalYearLgBudgetOutturnsByFiscalYearOpmLgBudgetOutturnDto) GetItem_Code() string {
	return v.Item_Code
}

// GetItem_Description returns LgBudgetOutturnsByFiscalYearLgBudgetOutturnsByFiscalYearOpmLgBudgetOutturnDto.Item_Description, and is useful for accessing the field via an interface.
func (v *LgBudgetOutturnsByFiscalYearLgBudgetOutturnsByFiscalYearOpmLgBudgetOutturnDto) GetItem_Description() string {
	return v.Item_Description
}

// GetApprovedBudget returns LgBudgetOutturnsByFiscalYearLgBudgetOutturnsByFiscalYearOpmLgBudgetOutturnDto.ApprovedBudget, and is useful for accessing the field via an interface.
func (v *LgBudgetOutturnsByFiscalYearLgBudgetOutturnsByFiscalYearOpmLgBudgetOutturnDto) GetApprovedBudget() float64 {
	return v.ApprovedBudget
}

// GetRevisedBudget returns LgBudgetOutturnsByFiscalYearLgBudgetOutturnsByFiscalYearOpmLgBudgetOutturnDto.RevisedBudget, and is useful for accessing the field via an interface.
func (v *LgBudgetOutturnsByFiscalYearLgBudgetOutturnsByFiscalYearOpmLgBudgetOutturnDto) GetRevisedBudget() float64 {
	return v.RevisedBudget
}

// GetQ1_Release returns LgBudgetOutturnsByFiscalYearLgBudgetOutturnsByFiscalYearOpmLgBudgetOutturnDto.Q1_Release, and is useful for accessing the field via an interface.
func (v *LgBudgetOutturnsByFiscalYearLgBudgetOutturnsByFiscalYearOpmLgBudgetOutturnDto) GetQ1_Release() float64 {
	return v.Q1_Release
}

// GetQ1_Expenditure returns LgBudgetOutturnsByFiscalYearLgBudgetOutturnsByFiscalYearOpmLgBudgetOutturnDto.Q1_Expenditure, and is useful for accessing the field via an interface.
func (v *LgBudgetOutturnsByFiscalYearLgBudgetOutturnsByFiscalYearOpmLgBudgetOutturnDto) GetQ1_Expenditure() float64 {
	return v.Q1_Expenditure
}

// GetQ2_Release returns LgBudgetOutturnsByFiscalYearLgBudgetOutturnsByFiscalYearOpmLgBudgetOutturnDto.Q2_Release, and is useful for accessing the field via an interface.
func (v *LgBudgetOutturnsByFiscalYearLgBudgetOutturnsByFiscalYearOpmLgBudgetOutturnDto) GetQ2_Release() float64 {
	return v.Q2_Release
}

// GetQ2_Expenditure returns LgBudgetOutturnsByFiscalYearLgBudgetOutturnsByFiscalYearOpmLgBudgetOutturnDto.Q2_Expenditure, and is useful for accessing the field via an interface.
func (v *LgBudgetOutturnsByFiscalYearLgBudgetOutturnsByFiscalYearOpmLgBudgetOutturnDto) GetQ2_Expenditure() float64 {
	return v.Q2_Expenditure
}

// GetQ3_Release returns LgBudgetOutturnsByFiscalYearLgBudgetOutturnsByFiscalYearOpmLgBudgetOutturnDto.Q3_Release, and is useful for accessing the field via an interface.
func (v *LgBudgetOutturnsByFiscalYearLgBudgetOutturnsByFiscalYearOpmLgBudgetOutturnDto) GetQ3_Release() float64 {
	return v.Q3_Release
}

// GetQ3_Expenditure returns LgBudgetOutturnsByFiscalYearLgBudgetOutturnsByFiscalYearOpmLgBudgetOutturnDto.Q3_Expenditure, and is useful for accessing the field via an interface.
func (v *LgBudgetOutturnsByFiscalYearLgBudgetOutturnsByFiscalYearOpmLgBudgetOutturnDto) GetQ3_Expenditure() float64 {
	return v.Q3_Expenditure
}

// GetQ4_Release returns LgBudgetOutturnsByFiscalYearLgBudgetOutturnsByFiscalYearOpmLgBudgetOutturnDto.Q4_Release, and is useful for accessing the field via an interface.
func (v *LgBudgetOutturnsByFiscalYearLgBudgetOutturnsByFiscalYearOpmLgBudgetOutturnDto) GetQ4_Release() float64 {
	return v.Q4_Release
}

// GetQ4_Expenditure returns LgBudgetOutturnsByFiscalYearLgBudgetOutturnsByFiscalYearOpmLgBudgetOutturnDto.Q4_Expenditure, and is useful for accessing the field via an interface.
func (v *LgBudgetOutturnsByFiscalYearLgBudgetOutturnsByFiscalYearOpmLgBudgetOutturnDto) GetQ4_Expenditure() float64 {
	return v.Q4_Expenditure
}

// LgBudgetOutturnsByFiscalYearResponse is returned by LgBudgetOutturnsByFiscalYear on success.
type LgBudgetOutturnsByFiscalYearResponse struct {
	LgBudgetOutturnsByFiscalYear []LgBudgetOutturnsByFiscalYearLgBudgetOutturnsByFiscalYearOpmLgBudgetOutturnDto `json:"lgBudgetOutturnsByFiscalYear"`
}

// GetLgBudgetOutturnsByFiscalYear returns LgBudgetOutturnsByFiscalYearResponse.LgBudgetOutturnsByFiscalYear, and is useful for accessing the field via an interface.
func (v *LgBudgetOutturnsByFiscalYearResponse) GetLgBudgetOutturnsByFiscalYear() []LgBudgetOutturnsByFiscalYearLgBudgetOutturnsByFiscalYearOpmLgBudgetOutturnDto {
	return v.LgBudgetOutturnsByFiscalYear
}

// LgBudgetOutturnsByVoteAndFiscalYearLgBudgetOutturnsByVoteAndFiscalYearOpmLgBudgetOutturnDto includes the requested fields of the GraphQL type OpmLgBudgetOutturnDto.
type LgBudgetOutturnsByVoteAndFiscalYearLgBudgetOutturnsByVoteAndFiscalYearOpmLgBudgetOutturnDto struct {
	Fiscal_Year               string  `json:"Fiscal_Year"`
	Vote_Code                 string  `json:"Vote_Code"`
	Vote_Name                 string  `json:"Vote_Name"`
	Programme_Code            string  `json:"Programme_Code"`
	Programme_Name            string  `json:"Programme_Name"`
	Department_Code           string  `json:"Department_Code"`
	Department_Name           string  `json:"Department_Name"`
	Project_Code              string  `json:"Project_Code"`
	Budget_Output_Code        string  `json:"Budget_Output_Code"`
	Budget_Output_Description string  `json:"Budget_Output_Description"`
	Item_Code                 string  `json:"Item_Code"`
	Item_Description          string  `json:"Item_Description"`
	ApprovedBudget            float64 `json:"ApprovedBudget"`
	RevisedBudget             float64 `json:"RevisedBudget"`
	Q1_Release                float64 `json:"Q1_Release"`
	Q1_Expenditure            float64 `json:"Q1_Expenditure"`
	Q2_Release                float64 `json:"Q2_Release"`
	Q2_Expenditure            float64 `json:"Q2_Expenditure"`
	Q3_Release                float64 `json:"Q3_Release"`
	Q3_Expenditure            float64 `json:"Q3_Expenditure"`
	Q4_Release                float64 `json:"Q4_Release"`
	Q4_Expenditure            float64 `json:"Q4_Expenditure"`
}

// GetFiscal_Year returns LgBudgetOutturnsByVoteAndFiscalYearLgBudgetOutturnsByVoteAndFiscalYearOpmLgBudgetOutturnDto.Fiscal_Year, and is useful for accessing the field via an interface.
func (v *LgBudgetOutturnsByVoteAndFiscalYearLgBudgetOutturnsByVoteAndFiscalYearOpmLgBudgetOutturnDto) GetFiscal_Year() string {
	return v.Fiscal_Year
}

// GetVote_Code returns LgBudgetOutturnsByVoteAndFiscalYearLgBudgetOutturnsByVoteAndFiscalYearOpmLgBudgetOutturnDto.Vote_Code, and is useful for accessing the field via an interface.
func (v *LgBudgetOutturnsByVoteAndFiscalYearLgBudgetOutturnsByVoteAndFiscalYearOpmLgBudgetOutturnDto) GetVote_Code() string {
	return v.Vote_Code
}

// GetVote_Name returns LgBudgetOutturnsByVoteAndFiscalYearLgBudgetOutturnsByVoteAndFiscalYearOpmLgBudgetOutturnDto.Vote_Name, and is useful for accessing the field via an interface.
func (v *LgBudgetOutturnsByVoteAndFiscalYearLgBudgetOutturnsByVoteAndFiscalYearOpmLgBudgetOutturnDto) GetVote_Name() string {
	return v.Vote_Name
}

// GetProgramme_Code returns LgBudgetOutturnsByVoteAndFiscalYearLgBudgetOutturnsByVoteAndFiscalYearOpmLgBudgetOutturnDto.Programme_Code, and is useful for accessing the field via an interface.
func (v *LgBudgetOutturnsByVoteAndFiscalYearLgBudgetOutturnsByVoteAndFiscalYearOpmLgBudgetOutturnDto) GetProgramme_Code() string {
	return v.Programme_Code
}

// GetProgramme_Name returns LgBudgetOutturnsByVoteAndFiscalYearLgBudgetOutturnsByVoteAndFiscalYearOpmLgBudgetOutturnDto.Programme_Name, and is useful for accessing the field via an interface.
func (v *LgBudgetOutturnsByVoteAndFiscalYearLgBudgetOutturnsByVoteAndFiscalYearOpmLgBudgetOutturnDto) GetProgramme_Name() string {
	return v.Programme_Name
}

// GetDepartment_Code returns LgBudgetOutturnsByVoteAndFiscalYearLgBudgetOutturnsByVoteAndFiscalYearOpmLgBudgetOutturnDto.Department_Code, and is useful for accessing the field via an interface.
func (v *LgBudgetOutturnsByVoteAndFiscalYearLgBudgetOutturnsByVoteAndFiscalYearOpmLgBudgetOutturnDto) GetDepartment_Code() string {
	return v.Department_Code
}

// GetDepartment_Name returns LgBudgetOutturnsByVoteAndFiscalYearLgBudgetOutturnsByVoteAndFiscalYearOpmLgBudgetOutturnDto.Department_Name, and is useful for accessing the field via an interface.
func (v *LgBudgetOutturnsByVoteAndFiscalYearLgBudgetOutturnsByVoteAndFiscalYearOpmLgBudgetOutturnDto) GetDepartment_Name() string {
	return v.Department_Name
}

// GetProject_Code returns LgBudgetOutturnsByVoteAndFiscalYearLgBudgetOutturnsByVoteAndFiscalYearOpmLgBudgetOutturnDto.Project_Code, and is useful for accessing the field via an interface.
func (v *LgBudgetOutturnsByVoteAndFiscalYearLgBudgetOutturnsByVoteAndFiscalYearOpmLgBudgetOutturnDto) GetProject_Code() string {
	return v.Project_Code
}

// GetBudget_Output_Code returns LgBudgetOutturnsByVoteAndFiscalYearLgBudgetOutturnsByVoteAndFiscalYearOpmLgBudgetOutturnDto.Budget_Output_Code, and is useful for accessing the field via an interface.
func (v *LgBudgetOutturnsByVoteAndFiscalYearLgBudgetOutturnsByVoteAndFiscalYearOpmLgBudgetOutturnDto) GetBudget_Output_Code() string {
	return v.Budget_Output_Code
}

// GetBudget_Output_Description returns LgBudgetOutturnsByVoteAndFiscalYearLgBudgetOutturnsByVoteAndFiscalYearOpmLgBudgetOutturnDto.Budget_Output_Description, and is useful for accessing the field via an interface.
func (v *LgBudgetOutturnsByVoteAndFiscalYearLgBudgetOutturnsByVoteAndFiscalYearOpmLgBudgetOutturnDto) GetBudget_Output_Description() string {
	return v.Budget_Output_Description
}

// GetItem_Code returns LgBudgetOutturnsByVoteAndFiscalYearLgBudgetOutturnsByVoteAndFiscalYearOpmLgBudgetOutturnDto.Item_Code, and is useful for accessing the field via an interface.
func (v *LgBudgetOutturnsByVoteAndFiscalYearLgBudgetOutturnsByVoteAndFiscalYearOpmLgBudgetOutturnDto) GetItem_Code() string {
	return v.Item_Code
}

// GetItem_Description returns LgBudgetOutturnsByVoteAndFiscalYearLgBudgetOutturnsByVoteAndFiscalYearOpmLgBudgetOutturnDto.Item_Description, and is useful for accessing the field via an interface.
func (v *LgBudgetOutturnsByVoteAndFiscalYearLgBudgetOutturnsByVoteAndFiscalYearOpmLgBudgetOutturnDto) GetItem_Description() string {
	return v.Item_Description
}

// GetApprovedBudget returns LgBudgetOutturnsByVoteAndFiscalYearLgBudgetOutturnsByVoteAndFiscalYearOpmLgBudgetOutturnDto.ApprovedBudget, and is useful for accessing the field via an interface.
func (v *LgBudgetOutturnsByVoteAndFiscalYearLgBudgetOutturnsByVoteAndFiscalYearOpmLgBudgetOutturnDto) GetApprovedBudget() float64 {
	return v.ApprovedBudget
}

// GetRevisedBudget returns LgBudgetOutturnsByVoteAndFiscalYearLgBudgetOutturnsByVoteAndFiscalYearOpmLgBudgetOutturnDto.RevisedBudget, and is useful for accessing the field via an interface.
func (v *LgBudgetOutturnsByVoteAndFiscalYearLgBudgetOutturnsByVoteAndFiscalYearOpmLgBudgetOutturnDto) GetRevisedBudget() float64 {
	return v.RevisedBudget
}

// GetQ1_Release returns LgBudgetOutturnsByVoteAndFiscalYearLgBudgetOutturnsByVoteAndFiscalYearOpmLgBudgetOutturnDto.Q1_Release, and is useful for accessing the field via an interface.
func (v *LgBudgetOutturnsByVoteAndFiscalYearLgBudgetOutturnsByVoteAndFiscalYearOpmLgBudgetOutturnDto) GetQ1_Release() float64 {
	return v.Q1_Release
}

// GetQ1_Expenditure returns LgBudgetOutturnsByVoteAndFiscalYearLgBudgetOutturnsByVoteAndFiscalYearOpmLgBudgetOutturnDto.Q1_Expenditure, and is useful for accessing the field via an interface.
func (v *LgBudgetOutturnsByVoteAndFiscalYearLgBudgetOutturnsByVoteAndFiscalYearOpmLgBudgetOutturnDto) GetQ1_Expenditure() float64 {
	return v.Q1_Expenditure
}

// GetQ2_Release returns LgBudgetOutturnsByVoteAndFiscalYearLgBudgetOutturnsByVoteAndFiscalYearOpmLgBudgetOutturnDto.Q2_Release, and is useful for accessing the field via an interface.
func (v *LgBudgetOutturnsByVoteAndFiscalYearLgBudgetOutturnsByVoteAndFiscalYearOpmLgBudgetOutturnDto) GetQ2_Release() float64 {
	return v.Q2_Release
}

// GetQ2_Expenditure returns LgBudgetOutturnsByVoteAndFiscalYearLgBudgetOutturnsByVoteAndFiscalYearOpmLgBudgetOutturnDto.Q2_Expenditure, and is useful for accessing the field via an interface.
func (v *LgBudgetOutturnsByVoteAndFiscalYearLgBudgetOutturnsByVoteAndFiscalYearOpmLgBudgetOutturnDto) GetQ2_Expenditure() float64 {
	return v.Q2_Expenditure
}

// GetQ3_Release returns LgBudgetOutturnsByVoteAndFiscalYearLgBudgetOutturnsByVoteAndFiscalYearOpmLgBudgetOutturnDto.Q3_Release, and is useful for accessing the field via an interface.
func (v *LgBudgetOutturnsByVoteAndFiscalYearLgBudgetOutturnsByVoteAndFiscalYearOpmLgBudgetOutturnDto) GetQ3_Release() float64 {
	return v.Q3_Release
}

// GetQ3_Expenditure returns LgBudgetOutturnsByVoteAndFiscalYearLgBudgetOutturnsByVoteAndFiscalYearOpmLgBudgetOutturnDto.Q3_Expenditure, and is useful for accessing the field via an interface.
func (v *LgBudgetOutturnsByVoteAndFiscalYearLgBudgetOutturnsByVoteAndFiscalYearOpmLgBudgetOutturnDto) GetQ3_Expenditure() float64 {
	return v.Q3_Expenditure
}

// GetQ4_Release returns LgBudgetOutturnsByVoteAndFiscalYearLgBudgetOutturnsByVoteAndFiscalYearOpmLgBudgetOutturnDto.Q4_Release, and is useful for accessing the field via an interface.
func (v *LgBudgetOutturnsByVoteAndFiscalYearLgBudgetOutturnsByVoteAndFiscalYearOpmLgBudgetOutturnDto) GetQ4_Release() float64 {
	return v.Q4_Release
}

// GetQ4_Expenditure returns LgBudgetOutturnsByVoteAndFiscalYearLgBudgetOutturnsByVoteAndFiscalYearOpmLgBudgetOutturnDto.Q4_Expenditure, and is useful for accessing the field via an interface.
func (v *LgBudgetOutturnsByVoteAndFiscalYearLgBudgetOutturnsByVoteAndFiscalYearOpmLgBudgetOutturnDto) GetQ4_Expenditure() float64 {
	return v.Q4_Expenditure
}

// LgBudgetOutturnsByVoteAndFiscalYearResponse is returned by LgBudgetOutturnsByVoteAndFiscalYear on success.
type LgBudgetOutturnsByVoteAndFiscalYearResponse struct {
	LgBudgetOutturnsByVoteAndFiscalYear []LgBudgetOutturnsByVoteAndFiscalYearLgBudgetOutturnsByVoteAndFiscalYearOpmLgBudgetOutturnDto `json:"lgBudgetOutturnsByVoteAndFiscalYear"`
}

// GetLgBudgetOutturnsByVoteAndFiscalYear returns LgBudgetOutturnsByVoteAndFiscalYearResponse.LgBudgetOutturnsByVoteAndFiscalYear, and is useful for accessing the field via an interface.
func (v *LgBudgetOutturnsByVoteAndFiscalYearResponse) GetLgBudgetOutturnsByVoteAndFiscalYear() []LgBudgetOutturnsByVoteAndFiscalYearLgBudgetOutturnsByVoteAndFiscalYearOpmLgBudgetOutturnDto {
	return v.LgBudgetOutturnsByVoteAndFiscalYear
}

// LgIFMSBudgetOutputsLgIFMSBudgetOutputsLgIFMSBudgetOutputsDto includes the requested fields of the GraphQL type LgIFMSBudgetOutputsDto.
type LgIFMSBudgetOutputsLgIFMSBudgetOutputsLgIFMSBudgetOutputsDto struct {
	Budget_Output_ID   float64   `json:"Budget_Output_ID"`
	Budget_Output_Code string    `json:"Budget_Output_Code"`
	Budget_Output_Name string    `json:"Budget_Output_Name"`
	Created_Date       time.Time `json:"Created_Date"`
}

// GetBudget_Output_ID returns LgIFMSBudgetOutputsLgIFMSBudgetOutputsLgIFMSBudgetOutputsDto.Budget_Output_ID, and is useful for accessing the field via an interface.
func (v *LgIFMSBudgetOutputsLgIFMSBudgetOutputsLgIFMSBudgetOutputsDto) GetBudget_Output_ID() float64 {
	return v.Budget_Output_ID
}

// GetBudget_Output_Code returns LgIFMSBudgetOutputsLgIFMSBudgetOutputsLgIFMSBudgetOutputsDto.Budget_Output_Code, and is useful for accessing the field via an interface.
func (v *LgIFMSBudgetOutputsLgIFMSBudgetOutputsLgIFMSBudgetOutputsDto) GetBudget_Output_Code() string {
	return v.Budget_Output_Code
}

// GetBudget_Output_Name returns LgIFMSBudgetOutputsLgIFMSBudgetOutputsLgIFMSBudgetOutputsDto.Budget_Output_Name, and is useful for accessing the field via an interface.
func (v *LgIFMSBudgetOutputsLgIFMSBudgetOutputsLgIFMSBudgetOutputsDto) GetBudget_Output_Name() string {
	return v.Budget_Output_Name
}

// GetCreated_Date returns LgIFMSBudgetOutputsLgIFMSBudgetOutputsLgIFMSBudgetOutputsDto.Created_Date, and is useful for accessing the field via an interface.
func (v *LgIFMSBudgetOutputsLgIFMSBudgetOutputsLgIFMSBudgetOutputsDto) GetCreated_Date() time.Time {
	return v.Created_Date
}

// LgIFMSBudgetOutputsResponse is returned by LgIFMSBudgetOutputs on success.
type LgIFMSBudgetOutputsResponse struct {
	LgIFMSBudgetOutputs []LgIFMSBudgetOutputsLgIFMSBudgetOutputsLgIFMSBudgetOutputsDto `json:"lgIFMSBudgetOutputs"`
}

// GetLgIFMSBudgetOutputs returns LgIFMSBudgetOutputsResponse.LgIFMSBudgetOutputs, and is useful for accessing the field via an interface.
func (v *LgIFMSBudgetOutputsResponse) GetLgIFMSBudgetOutputs() []LgIFMSBudgetOutputsLgIFMSBudgetOutputsLgIFMSBudgetOutputsDto {
	return v.LgIFMSBudgetOutputs
}

// LgIFMSVotesLgIFMSVotesLgIFMSVotesDto includes the requested fields of the GraphQL type LgIFMSVotesDto.
type LgIFMSVotesLgIFMSVotesLgIFMSVotesDto struct {
	Vote_ID      float64   `json:"Vote_ID"`
	Vote_Code    string    `json:"Vote_Code"`
	Vote_Name    string    `json:"Vote_Name"`
	Created_Date time.Time `json:"Created_Date"`
}

// GetVote_ID returns LgIFMSVotesLgIFMSVotesLgIFMSVotesDto.Vote_ID, and is useful for accessing the field via an interface.
func (v *LgIFMSVotesLgIFMSVotesLgIFMSVotesDto) GetVote_ID() float64 { return v.Vote_ID }

// GetVote_Code returns LgIFMSVotesLgIFMSVotesLgIFMSVotesDto.Vote_Code, and is useful for accessing the field via an interface.
func (v *LgIFMSVotesLgIFMSVotesLgIFMSVotesDto) GetVote_Code() string { return v.Vote_Code }

// GetVote_Name returns LgIFMSVotesLgIFMSVotesLgIFMSVotesDto.Vote_Name, and is useful for accessing the field via an interface.
func (v *LgIFMSVotesLgIFMSVotesLgIFMSVotesDto) GetVote_Name() string { return v.Vote_Name }

// GetCreated_Date returns LgIFMSVotesLgIFMSVotesLgIFMSVotesDto.Created_Date, and is useful for accessing the field via an interface.
func (v *LgIFMSVotesLgIFMSVotesLgIFMSVotesDto) GetCreated_Date() time.Time { return v.Created_Date }

// LgIFMSVotesResponse is returned by LgIFMSVotes on success.
type LgIFMSVotesResponse struct {
	LgIFMSVotes []LgIFMSVotesLgIFMSVotesLgIFMSVotesDto `json:"lgIFMSVotes"`
}

// GetLgIFMSVotes returns LgIFMSVotesResponse.LgIFMSVotes, and is useful for accessing the field via an interface.
func (v *LgIFMSVotesResponse) GetLgIFMSVotes() []LgIFMSVotesLgIFMSVotesLgIFMSVotesDto {
	return v.LgIFMSVotes
}

// LoginLoginAuthDto includes the requested fields of the GraphQL type AuthDto.
type LoginLoginAuthDto struct {
	Access_token  string                       `json:"access_token"`
	Refresh_token string                       `json:"refresh_token"`
	User          LoginLoginAuthDtoUserUserDto `json:"user"`
}

// GetAccess_token returns LoginLoginAuthDto.Access_token, and is useful for accessing the field via an interface.
func (v *LoginLoginAuthDto) GetAccess_token() string { return v.Access_token }

// GetRefresh_token returns LoginLoginAuthDto.Refresh_token, and is useful for accessing the field via an interface.
func (v *LoginLoginAuthDto) GetRefresh_token() string { return v.Refresh_token }

// GetUser returns LoginLoginAuthDto.User, and is useful for accessing the field via an interface.
func (v *LoginLoginAuthDto) GetUser() LoginLoginAuthDtoUserUserDto { return v.User }

// LoginLoginAuthDtoUserUserDto includes the requested fields of the GraphQL type UserDto.
type LoginLoginAuthDtoUserUserDto struct {
	User_ID    float64 `json:"User_ID"`
	User_Name  string  `json:"User_Name"`
	First_Name string  `json:"First_Name"`
	Last_Name  string  `json:"Last_Name"`
	Email      string  `json:"Email"`
}

// GetUser_ID returns LoginLoginAuthDtoUserUserDto.User_ID, and is useful for accessing the field via an interface.
func (v *LoginLoginAuthDtoUserUserDto) GetUser_ID() float64 { return v.User_ID }

// GetUser_Name returns LoginLoginAuthDtoUserUserDto.User_Name, and is useful for accessing the field via an interface.
func (v *LoginLoginAuthDtoUserUserDto) GetUser_Name() string { return v.User_Name }

// GetFirst_Name returns LoginLoginAuthDtoUserUserDto.First_Name, and is useful for accessing the field via an interface.
func (v *LoginLoginAuthDtoUserUserDto) GetFirst_Name() string { return v.First_Name }

// GetLast_Name returns LoginLoginAuthDtoUserUserDto.Last_Name, and is useful for accessing the field via an interface.
func (v *LoginLoginAuthDtoUserUserDto) GetLast_Name() string { return v.Last_Name }

// GetEmail returns LoginLoginAuthDtoUserUserDto.Email, and is useful for accessing the field via an interface.
func (v *LoginLoginAuthDtoUserUserDto) GetEmail() string { return v.Email }

// LoginResponse is returned by Login on success.
type LoginResponse struct {
	Login LoginLoginAuthDto `json:"login"`
}

// GetLogin returns LoginResponse.Login, and is useful for accessing the field via an interface.
func (v *LoginResponse) GetLogin() LoginLoginAuthDto { return v.Login }

// RefreshRefreshTokenAuthDto includes the requested fields of the GraphQL type AuthDto.
type RefreshRefreshTokenAuthDto struct {
	Access_token  string `json:"access_token"`
	Refresh_token string `json:"refresh_token"`
}

// GetAccess_token returns RefreshRefreshTokenAuthDto.Access_token, and is useful for accessing the field via an interface.
func (v *RefreshRefreshTokenAuthDto) GetAccess_token() string { return v.Access_token }

// GetRefresh_token returns RefreshRefreshTokenAuthDto.Refresh_token, and is useful for accessing the field via an interface.
func (v *RefreshRefreshTokenAuthDto) GetRefresh_token() string { return v.Refresh_token }

// RefreshResponse is returned by Refresh on success.
type RefreshResponse struct {
	RefreshToken RefreshRefreshTokenAuthDto `json:"refreshToken"`
}

// GetRefreshToken returns RefreshResponse.RefreshToken, and is useful for accessing the field via an interface.
func (v *RefreshResponse) GetRefreshToken() RefreshRefreshTokenAuthDto { return v.RefreshToken }

// __CgBudgetOutturnsByFiscalYearInput is used internally by genqlient
type __CgBudgetOutturnsByFiscalYearInput struct {
	Fy string `json:"fy"`
}

// GetFy returns __CgBudgetOutturnsByFiscalYearInput.Fy, and is useful for accessing the field via an interface.
func (v *__CgBudgetOutturnsByFiscalYearInput) GetFy() string { return v.Fy }

// __CgPiapIndicatorProjectionsByFiscalYearInput is used internally by genqlient
type __CgPiapIndicatorProjectionsByFiscalYearInput struct {
	Fy string `json:"fy"`
}

// GetFy returns __CgPiapIndicatorProjectionsByFiscalYearInput.Fy, and is useful for accessing the field via an interface.
func (v *__CgPiapIndicatorProjectionsByFiscalYearInput) GetFy() string { return v.Fy }

// __CgProgrammeOutcomeIndicatorProjectionsByFiscalYearInput is used internally by genqlient
type __CgProgrammeOutcomeIndicatorProjectionsByFiscalYearInput struct {
	Fy string `json:"fy"`
}

// GetFy returns __CgProgrammeOutcomeIndicatorProjectionsByFiscalYearInput.Fy, and is useful for accessing the field via an interface.
func (v *__CgProgrammeOutcomeIndicatorProjectionsByFiscalYearInput) GetFy() string { return v.Fy }

// __LgBudgetOutturnsByFiscalYearInput is used internally by genqlient
type __LgBudgetOutturnsByFiscalYearInput struct {
	Fy string `json:"fy"`
}

// GetFy returns __LgBudgetOutturnsByFiscalYearInput.Fy, and is useful for accessing the field via an interface.
func (v *__LgBudgetOutturnsByFiscalYearInput) GetFy() string { return v.Fy }

// __LgBudgetOutturnsByVoteAndFiscalYearInput is used internally by genqlient
type __LgBudgetOutturnsByVoteAndFiscalYearInput struct {
	Vote string `json:"vote"`
	Fy   string `json:"fy"`
}

// GetVote returns __LgBudgetOutturnsByVoteAndFiscalYearInput.Vote, and is useful for accessing the field via an interface.
func (v *__LgBudgetOutturnsByVoteAndFiscalYearInput) GetVote() string { return v.Vote }

// GetFy returns __LgBudgetOutturnsByVoteAndFiscalYearInput.Fy, and is useful for accessing the field via an interface.
func (v *__LgBudgetOutturnsByVoteAndFiscalYearInput) GetFy() string { return v.Fy }

// __LoginInput is used internally by genqlient
type __LoginInput struct {
	User string `json:"user"`
	Pass string `json:"pass"`
	Ip   string `json:"ip"`
}

// GetUser returns __LoginInput.User, and is useful for accessing the field via an interface.
func (v *__LoginInput) GetUser() string { return v.User }

// GetPass returns __LoginInput.Pass, and is useful for accessing the field via an interface.
func (v *__LoginInput) GetPass() string { return v.Pass }

// GetIp returns __LoginInput.Ip, and is useful for accessing the field via an interface.
func (v *__LoginInput) GetIp() string { return v.Ip }

// __RefreshInput is used internally by genqlient
type __RefreshInput struct {
	At string `json:"at"`
	Rt string `json:"rt"`
}

// GetAt returns __RefreshInput.At, and is useful for accessing the field via an interface.
func (v *__RefreshInput) GetAt() string { return v.At }

// GetRt returns __RefreshInput.Rt, and is useful for accessing the field via an interface.
func (v *__RefreshInput) GetRt() string { return v.Rt }

// The query executed by CgBudgetOutturnsByFiscalYear.
const CgBudgetOutturnsByFiscalYear_Operation = `
query CgBudgetOutturnsByFiscalYear ($fy: String!) {
	cgBudgetOutturnByFiscalYear(Fiscal_Year: $fy) {
		Fiscal_Year
		Vote_Code
		Vote_Name
		Programme_Code
		Programme_Name
		Department_Code
		Department_Name
		Project_Code
		Budget_Output_Code
		Budget_Output_Description
		Item_Code
		Item_Description
		ApprovedBudget
		RevisedBudget
		Q1Release
		Q1Expenditure
		Q2Release
		Q2Expenditure
		Q3Release
		Q3Expenditure
		Q4Release
		Q4Expenditure
	}
}
`

func CgBudgetOutturnsByFiscalYear(
	ctx_ context.Context,
	client_ graphql.Client,
	fy string,
) (data_ *CgBudgetOutturnsByFiscalYearResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "CgBudgetOutturnsByFiscalYear",
		Query:  CgBudgetOutturnsByFiscalYear_Operation,
		Variables: &__CgBudgetOutturnsByFiscalYearInput{
			Fy: fy,
		},
	}

	data_ = &CgBudgetOutturnsByFiscalYearResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by CgPiapIndicatorProjectionsByFiscalYear.
const CgPiapIndicatorProjectionsByFiscalYear_Operation = `
query CgPiapIndicatorProjectionsByFiscalYear ($fy: String!) {
	cgPiapIndicatorProjectionsByFiscalYear(Fiscal_Year: $fy) {
		Fiscal_Year
		Vote_Code
		Vote_Name
		Programme_Code
		Programme_Name
		Department_Code
		Department_Name
		Budget_Output_Code
		Budget_Output_Description
		Target_Y1
		PIAP_Output_Code
		PIAP_Output_Description
		PIAP_Output_Indicator_Code
		PIAP_Output_Indicator_Name
		Q1_Actual_Target
		Q1_Reason_For_Variation
		Q2_Actual_Target
		Q2_Reason_For_Variation
		Q2_Cum_Performance
		Q3_Actual_Target
		Q3_Reason_For_Variation
		Q3_Cum_Performance
		Q4_Actual_Target
		Q4_Reason_For_Variation
		Q4_Cum_Performance
	}
}
`

func CgPiapIndicatorProjectionsByFiscalYear(
	ctx_ context.Context,
	client_ graphql.Client,
	fy string,
) (data_ *CgPiapIndicatorProjectionsByFiscalYearResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "CgPiapIndicatorProjectionsByFiscalYear",
		Query:  CgPiapIndicatorProjectionsByFiscalYear_Operation,
		Variables: &__CgPiapIndicatorProjectionsByFiscalYearInput{
			Fy: fy,
		},
	}

	data_ = &CgPiapIndicatorProjectionsByFiscalYearResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by CgProgrammeOutcomeIndicatorProjectionsByFiscalYear.
const CgProgrammeOutcomeIndicatorProjectionsByFiscalYear_Operation = `
query CgProgrammeOutcomeIndicatorProjectionsByFiscalYear ($fy: String!) {
	cgProgrammeOutcomeIndicatorProjectionsByFiscalYear(Fiscal_Year: $fy) {
		Fiscal_Year
		Programme_Code
		Programme_Name
		Programme_Objective_Code
		Programme_Objective_Name
		Programme_Outcome_Code
		Programme_Outcome_Description
		Programme_Outcome_Indicator_Code
		Programme_Outcome_Indicator_Description
		Target_Y1
		Q2_Actual
		Q2_Reason_For_Variation
		Q4_Actual
		Q4_Reason_For_Variation
	}
}
`

func CgProgrammeOutcomeIndicatorProjectionsByFiscalYear(
	ctx_ context.Context,
	client_ graphql.Client,
	fy string,
) (data_ *CgProgrammeOutcomeIndicatorProjectionsByFiscalYearResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "CgProgrammeOutcomeIndicatorProjectionsByFiscalYear",
		Query:  CgProgrammeOutcomeIndicatorProjectionsByFiscalYear_Operation,
		Variables: &__CgProgrammeOutcomeIndicatorProjectionsByFiscalYearInput{
			Fy: fy,
		},
	}

	data_ = &CgProgrammeOutcomeIndicatorProjectionsByFiscalYearResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by LgBudgetOutturnsByFiscalYear.
const LgBudgetOutturnsByFiscalYear_Operation = `
query LgBudgetOutturnsByFiscalYear ($fy: String!) {
	lgBudgetOutturnsByFiscalYear(Fiscal_Year: $fy) {
		Fiscal_Year
		Vote_Code
		Vote_Name
		Programme_Code
		Programme_Name
		Department_Code
		Department_Name
		Project_Code
		Budget_Output_Code
		Budget_Output_Description
		Item_Code
		Item_Description
		ApprovedBudget
		RevisedBudget
		Q1_Release
		Q1_Expenditure
		Q2_Release
		Q2_Expenditure
		Q3_Release
		Q3_Expenditure
		Q4_Release
		Q4_Expenditure
	}
}
`

func LgBudgetOutturnsByFiscalYear(
	ctx_ context.Context,
	client_ graphql.Client,
	fy string,
) (data_ *LgBudgetOutturnsByFiscalYearResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "LgBudgetOutturnsByFiscalYear",
		Query:  LgBudgetOutturnsByFiscalYear_Operation,
		Variables: &__LgBudgetOutturnsByFiscalYearInput{
			Fy: fy,
		},
	}

	data_ = &LgBudgetOutturnsByFiscalYearResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by LgBudgetOutturnsByVoteAndFiscalYear.
const LgBudgetOutturnsByVoteAndFiscalYear_Operation = `
query LgBudgetOutturnsByVoteAndFiscalYear ($vote: String!, $fy: String!) {
	lgBudgetOutturnsByVoteAndFiscalYear(Vote_Code: $vote, Fiscal_Year: $fy) {
		Fiscal_Year
		Vote_Code
		Vote_Name
		Programme_Code
		Programme_Name
		Department_Code
		Department_Name
		Project_Code
		Budget_Output_Code
		Budget_Output_Description
		Item_Code
		Item_Description
		ApprovedBudget
		RevisedBudget
		Q1_Release
		Q1_Expenditure
		Q2_Release
		Q2_Expenditure
		Q3_Release
		Q3_Expenditure
		Q4_Release
		Q4_Expenditure
	}
}
`

func LgBudgetOutturnsByVoteAndFiscalYear(
	ctx_ context.Context,
	client_ graphql.Client,
	vote string,
	fy string,
) (data_ *LgBudgetOutturnsByVoteAndFiscalYearResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "LgBudgetOutturnsByVoteAndFiscalYear",
		Query:  LgBudgetOutturnsByVoteAndFiscalYear_Operation,
		Variables: &__LgBudgetOutturnsByVoteAndFiscalYearInput{
			Vote: vote,
			Fy:   fy,
		},
	}

	data_ = &LgBudgetOutturnsByVoteAndFiscalYearResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by LgIFMSBudgetOutputs.
const LgIFMSBudgetOutputs_Operation = `
query LgIFMSBudgetOutputs {
	lgIFMSBudgetOutputs {
		Budget_Output_ID
		Budget_Output_Code
		Budget_Output_Name
		Created_Date
	}
}
`

func LgIFMSBudgetOutputs(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *LgIFMSBudgetOutputsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "LgIFMSBudgetOutputs",
		Query:  LgIFMSBudgetOutputs_Operation,
	}

	data_ = &LgIFMSBudgetOutputsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by LgIFMSVotes.
const LgIFMSVotes_Operation = `
query LgIFMSVotes {
	lgIFMSVotes {
		Vote_ID
		Vote_Code
		Vote_Name
		Created_Date
	}
}
`

func LgIFMSVotes(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *LgIFMSVotesResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "LgIFMSVotes",
		Query:  LgIFMSVotes_Operation,
	}

	data_ = &LgIFMSVotesResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by Login.
const Login_Operation = `
mutation Login ($user: String!, $pass: String!, $ip: String!) {
	login(data: {User_Name:$user,Password:$pass,ipAddress:$ip}) {
		access_token
		refresh_token
		user {
			User_ID
			User_Name
			First_Name
			Last_Name
			Email
		}
	}
}
`

func Login(
	ctx_ context.Context,
	client_ graphql.Client,
	user string,
	pass string,
	ip string,
) (data_ *LoginResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "Login",
		Query:  Login_Operation,
		Variables: &__LoginInput{
			User: user,
			Pass: pass,
			Ip:   ip,
		},
	}

	data_ = &LoginResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by Refresh.
const Refresh_Operation = `
mutation Refresh ($at: String!, $rt: String!) {
	refreshToken(data: {access_token:$at,refresh_token:$rt}) {
		access_token
		refresh_token
	}
}
`

func Refresh(
	ctx_ context.Context,
	client_ graphql.Client,
	at string,
	rt string,
) (data_ *RefreshResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "Refresh",
		Query:  Refresh_Operation,
		Variables: &__RefreshInput{
			At: at,
			Rt: rt,
		},
	}

	data_ = &RefreshResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
